# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release

sudo: required
cache: packages

before_install:
  - sudo apt-get update
  - sudo apt-get install libcurl4-openssl-dev -y

r_packages:
  - devtools
  - withr
  - covr
  - curl

after_success:
  - Rscript -e 'covr::codecov(quiet=FALSE)'

notifications:
  email: false